### PR TITLE
Various update for new internal driver

### LINKED ISSUE #46: Pass the throttling parameters into the job name
With the introduction of CPU & Network throttling, we want to make sure that users are able to run tests with various CPU and network combinations as part of the same build. Unfortunately, currently, independently of the settings with which speedo runs the job name remains the same thus making it impossible to find performance regressions for each of the test cases separately since each setting has a direct impact on the metrics. 

AC:
* Pass the network and CPU throttling parameters directly into the test name so that users are able to run tests across multiple throttling parameters as part of the same build.

### LINKED ISSUE #49: Sessions in SL not properly closed after an error
When using Speedo I sometimes get an error `unknown error` like in the logs below. When I look at the SL dashboard the instances are still running and I or need to stop them manually or need to wait till they time-out.
Can this be handled by Speedo?

```log
➜ ✗ speedo run http://www.wswebcreation.nl
✔ Start performance test run with user wim.selles on page http://www.wswebcreation.nl...
⠼ Couldn't find baseline for job with name Performance test for http://www.wswebcreation.nl, creating baseline...speedo run [params...] <site>

Run performance tests on any website.

Options:
  --version               Show version number                          [boolean]
  --help, -h              prints speedo help menu                      [boolean]
  --user, -u              your Sauce Labs username
  --key, -k               your Sauce Labs user key
  --region, -r            your Sauce Labs datacenter region, the following
                          regions are available: `us-west-1` (short `us`),
                          `eu-central-1` (short `eu`)            [default: "us"]
  --logDir, -l            directory to store logs from testrun
  --traceLogs, -t         if set runner downloads tracing logs for further
                          investigations
  --platformName, -p      the platform the performance test should run in (e.g.
                          "Windows 10")                  [default: "Windows 10"]
  --browserVersion, -v    the browser version of Chrome the performance test
                          should run in (e.g. "latest")      [default: "latest"]
  --build, -b             name of the build you want to run your performance
                          test in
  --name, -n              name of your performance test
  --metric, -m            metric that you want to check (multiple possible)
                                                               [default: "load"]
  --all                   check on all metrics        [boolean] [default: false]
  --throttleNetwork       throttle network speed for your test (e.g. "Good 3G")
                                                            [default: "Good 3G"]
  --throttleCpu           throttle cpu speed for your test (e.g. "4" for 1/4
                          speed)                                    [default: 4]
  --retry                 amount of retries for failing performance tests
                                                           [number] [default: 0]
  --tunnelIdentifier, -i  identifier for Sauce Connect tunnel to run performance
                          tests for local hosted apps
  --parentTunnel          username of parent running Sauce Connect tunnel

{ unknown error: Something went wrong with recording the trace over your page load. Please run the command again.
    at getErrorFromResponseBody (/Users/wimselles/.nvm/versions/node/v10.15.2/lib/node_modules/speedo/node_modules/webdriver/build/utils.js:349:10)
    at Request._callback (/Users/wimselles/.nvm/versions/node/v10.15.2/lib/node_modules/speedo/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/Users/wimselles/.nvm/versions/node/v10.15.2/lib/node_modules/speedo/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/Users/wimselles/.nvm/versions/node/v10.15.2/lib/node_modules/speedo/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/Users/wimselles/.nvm/versions/node/v10.15.2/lib/node_modules/speedo/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13) name: 'unknown error' }
```

### PR DESCRIPTION
**Pull request by christian-bromann**
As we are rolling out improvements with our internal Chromedriver we have to adjust some things , e.g. metrics etc. to the speedo tool to make it work properly. Some other fixes within this PR are:

- retry logic if [`assertPerformance`](https://webdriver.io/docs/api/saucelabs.html#assertperformance) fails due to tracing issue (e.g. `NO_NAVSTART`) - fixes #49
- make runtime profile more visible in std out - fixes #46
- make Lighthouse Performance Score default comparison metric
- run tests with w3c caps

### CODE REVIEW

File: src/runner.js [hunk 1]
```diff
@@ -3,14 +3,25 @@ import { remote } from 'webdriverio'
...
     const sauceOptions = {
-        name, build, extendedDebugging: true, capturePerformance: true,
-        ...(tunnelIdentifier ? { tunnelIdentifier } : {}),
-        ...(parentTunnel ? { parentTunnel } : {})
+        'sauce:options': {
+            name,
+            build,
+            extendedDebugging: true,
+            capturePerformance: true,
+            crmuxdriverVersion: 'beta',
```
Comment (adambabik) [inline src/runner.js]: Can we select this through argv? (We can do it as a separate PR as well)

File: src/runner.js [hunk 2]
```diff
@@ -35,7 +47,16 @@ export default async function runPerformanceTest (username, accessKey, argv, nam
...
+    try {
+        const result = await browser.assertPerformance(name, metrics)
+        await browser.deleteSession()
+        return { sessionId, result }
+    } catch (e) {
+        await browser.deleteSession()
+
+        // log data couldn't be fetched due to a tracing issue
+        // run test again:
+        return runPerformanceTest(username, accessKey, argv, name, build, logDir)
```
Comment (adambabik) [inline src/runner.js]: Should we somehow put a limit on how many times it can retry? Or it's on the user who should hit `CTRL-C`? If the latter, maybe we should print a log saying something like "retrying because of ..."`?

File: src/utils.js [hunk 3]
```diff
@@ -38,13 +39,15 @@ export const printResult = function (result, performanceLog, metrics, /* istanbu
...
-        const output = `${metric}: ${formatMetric[metric](value || 0)}`
+        const sanitizeFn = metric !== 'score' ? prettyMs : SCORE_SANITIZER
+        const output = `${metric}: ${sanitizeFn(value || 0)}`
         log(metrics.includes(metric) ? output : ctx.gray(output))
     }
 
     const resultDetails = []
     for (const [metric, { actual, lowerLimit, upperLimit }] of Object.entries(result.details)) {
-        resultDetails.push(`Expected ${metric} to be between ${formatMetric[metric](lowerLimit)} and ${formatMetric[metric](upperLimit)} but was actually ${formatMetric[metric](actual)}`)
+        const sanitizeFn = metric !== 'score' ? prettyMs : SCORE_SANITIZER
```
Comment (adambabik) [inline src/utils.js]: It repeats a few times, maybe:
```js
const sanitizeFn = getSanitizeFn(metric, default=prettyMs)
```

File: src/runner.js (hunk 1 above)
Comment (christian-bromann) [reply src/runner.js]: This is temporary. Once we released the our internal driver as stable I make a new PR removing this capability or make it configurable via parameter.

File: src/runner.js (hunk 2 above)
Comment (christian-bromann) [reply src/runner.js]: I added a limit of max 3 retries
